"""initial_schema

Revision ID: 445fb2a061cf
Revises: 
Create Date: 2026-03-02 20:07:19.593499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445fb2a061cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'observing', 'closed', name='casestatus'), nullable=False),
    sa.Column('hotness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_feeds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('feed_type', sa.Enum('rss', 'api', 'scraper', name='feedtype'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('parse_config', sa.JSON(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('normal', 'warning', 'offline', name='feedstatus'), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('case_tags',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'tag_id')
    )
    op.create_table('event_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_case_time', 'event_nodes', ['case_id', 'event_time'], unique=False)
    op.create_index('idx_event_time', 'event_nodes', ['event_time'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.Enum('government', 'mainstream_media', 'academic', 'local_media', 'social_media', 'unknown', name='sourcetype'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('has_false_history', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_feed_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_feed_id'], ['data_feeds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credibility_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_node_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.Enum('high', 'medium', 'low', 'unverified', name='credibilitylevel'), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('timeliness_score', sa.Float(), nullable=False),
    sa.Column('cross_verify_score', sa.Float(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('conflict_sources_json', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_node_id'], ['event_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_node_sources',
    sa.Column('event_node_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_node_id'], ['event_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_node_id', 'source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_node_sources')
    op.drop_table('credibility_assessments')
    op.drop_table('sources')
    op.drop_index('idx_event_time', table_name='event_nodes')
    op.drop_index('idx_event_case_time', table_name='event_nodes')
    op.drop_table('event_nodes')
    op.drop_table('case_tags')
    op.drop_table('tags')
    op.drop_table('data_feeds')
    op.drop_table('cases')
    # ### end Alembic commands ###
