"""add_is_builtin_to_data_feeds

Revision ID: bb98270190b8
Revises: 445fb2a061cf
Create Date: 2026-03-11 15:59:50.410168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb98270190b8'
down_revision: Union[str, None] = '445fb2a061cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_feeds', sa.Column('is_builtin', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_feeds', 'is_builtin')
    # ### end Alembic commands ###
